#!/bin/bash

# Source the .env file from the infra directory
source $(dirname "$0")/../.env

# Set GitHub secrets using values from .env
gh secret set AWS_ACCOUNT_ID --body "$AWS_ACCOUNT_ID"
gh secret set APP_NAME --body "$APP_NAME"
gh secret set AWS_REGION --body "$AWS_REGION"
gh secret set ROLE_TO_ASSUME --body "$ROLE_TO_ASSUME"
gh secret set S3_BUCKET_NAME --body "$S3_BUCKET_NAME"
gh secret set CLOUDFRONT_DISTRIBUTION_ID --body "$CLOUDFRONT_DISTRIBUTION_ID"
