#!/bin/bash

# Delete existing secrets if they exist, suppress errors, and print var name
gh secret remove AWS_ACCOUNT_ID 2>/dev/null && echo "Deleted AWS_ACCOUNT_ID"
gh secret remove AWS_REGION 2>/dev/null && echo "Deleted AWS_REGION"
gh secret remove APP_NAME 2>/dev/null && echo "Deleted APP_NAME"
gh secret remove ROLE_TO_ASSUME 2>/dev/null && echo "Deleted ROLE_TO_ASSUME"
gh secret remove CLOUDFRONT_DISTRIBUTION_ID 2>/dev/null && echo "Deleted CLOUDFRONT_DISTRIBUTION_ID"
gh secret remove S3_BUCKET_NAME 2>/dev/null && echo "Deleted S3_BUCKET_NAME"

