#!/bin/bash

# Delete existing secrets if they exist
gh secret remove AWS_ACCOUNT_ID 
gh secret remove AWS_REGION 
gh secret remove APP_NAME 
gh secret remove ROLE_TO_ASSUME 
gh secret remove CLOUDFRONT_DISTRIBUTION_ID 
gh secret remove S3_BUCKET_NAME 

