name: Simple Deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to use'
        required: true
        default: 'dev'
  push:
    branches:
      - main
jobs:
  apply:
    name: Test AWS Credentials
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}  # Use the environment from the workflow_dispatch input
    env:
      AWS_DEFAULT_REGION: "us-east-1"
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Test AWS Credentials
        run: |
          aws sts get-caller-identity
