name: Simple Deploy
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - sergio-pichardo-cloud-deploymnt-challenge
permissions:
  id-token: write
  contents: read
env:
  AWS_ACCOUNT_ID: "152725004650"
  AWS_REGION: "us-east-1"
jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/LCM-ChallengeGitHubActionsRole
          aws-region: ${{ env.AWS_REGION }}
      - name: List all S3 buckets
        run: |
          aws s3 ls

    
